name: Build OpenSSL for iOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-openssl-ios:
    name: Build OpenSSL for iOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install automake libtool
      working-directory: ${{ runner.workspace }}

    - name: Set the correct Xcode version
      run: |
        sudo xcode-select --switch /Applications/Xcode_15.4.app
      working-directory: ${{ runner.workspace }}

    - name: Install Xcode Command Line Tools
      run: |
        xcode-select --install || echo "Xcode Command Line Tools are already installed"
      working-directory: ${{ runner.workspace }}

    - name: Accept Xcode License
      run: sudo xcodebuild -license accept
      working-directory: ${{ runner.workspace }}

    - name: Check Available SDKs
      run: |
        xcode-select -p
        xcrun --sdk iphoneos --show-sdk-path || echo "SDK iphoneos not found"
        xcrun --sdk iphonesimulator --show-sdk-path || echo "SDK iphonesimulator not found"
      working-directory: ${{ runner.workspace }}

    - name: Configure and Build OpenSSL for iOS
      env:
        SDK_PATH: "/Applications/Xcode_15.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk"
        MIN_IOS_VERSION: 12.0
        ARCHS: "arm64 arm64e x86_64"
        BUILD_DIR: build-ios
      run: |
        set -e

        # Set paths for the build
        OPENSSL_DIR=${PWD}/openssl
        OUTPUT_DIR=${PWD}/${BUILD_DIR}
        mkdir -p "${OUTPUT_DIR}"

        for ARCH in $ARCHS; do
          if [[ "$ARCH" == "x86_64" ]]; then
            PLATFORM="iPhoneSimulator"
          else
            PLATFORM="iPhoneOS"
          fi

          # Set SDK paths
          export CROSS_TOP="${SDK_PATH%/SDKs/*}/SDKs"
          export CROSS_SDK="${PLATFORM}17.5.sdk"
          export BUILD_TOOLS="${SDK_PATH%/SDKs/*}/usr/bin"

          # Configure OpenSSL for the target architecture
          cd "$OPENSSL_DIR"
          ./Configure iphoneos-cross no-shared no-dso no-hw no-engine \
            --prefix="${OUTPUT_DIR}/${ARCH}" \
            --openssldir="${OUTPUT_DIR}/${ARCH}/ssl"

          # Build OpenSSL
          make clean
          make -j$(sysctl -n hw.logicalcpu)
          make install_sw
        done
      working-directory: ${{ runner.workspace }}

    - name: Archive build output
      run: |
        tar -czf openssl-ios-binaries.tar.gz -C ${BUILD_DIR} .
        mkdir -p artifacts
        mv openssl-ios-binaries.tar.gz artifacts/
      working-directory: ${{ runner.workspace }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: openssl-ios-binaries
        path: artifacts/openssl-ios-binaries.tar.gz
